### ISSUE TITLE
zooming browser break everything

### ISSUE THREAD

**Issue by rohmanhm** [djavaweb/unobuilder#28]
![image](https://cloud.githubusercontent.com/assets/7524911/23776838/4462ad8c-0563-11e7-8e41-0dcc8ddcd0b8.png)
When I zooming out your app in my browser, I think I found a bug.
Look the line above add new block button
I think you must use `rem` instead of `px` 😄  if it's truly CSS bug.

What do you think about this? @oknoorap 

References:
https://zellwk.com/blog/media-query-units/
https://css-tricks.com/rem-global-em-local/

**Comment by rohmanhm** [comment]
Oh snap, I found another bug again when zooming out my browser.
I can't drag the component. I think the offset of the component changing.

**Comment by oknoorap** [comment]
it's element selector tools, need to be reselect element.
